/**
 * Common Tool Labels
 */

import { STATUS_LABEL } from "../../../core/constants/status-labels.js";

export const TOOL_LABEL = {
    ERROR: STATUS_LABEL.ERROR,
    WARNING: STATUS_LABEL.WARNING,
    INFO: STATUS_LABEL.INFO,
    HINT: STATUS_LABEL.HINT,
    SUCCESS: STATUS_LABEL.SUCCESS,
    FAILED: STATUS_LABEL.FAILED,
    CLEAN: STATUS_LABEL.CLEAN,
    TIMEOUT: STATUS_LABEL.TIMEOUT,
    DONE: STATUS_LABEL.DONE,
    PENDING: STATUS_LABEL.PENDING,
    RUNNING: STATUS_LABEL.RUNNING,
} as const;

